server:
  port: 8080 #单体项目的端口就是8080
spring:
  application:
    name: gateway #微服务名称
  cloud:
    nacos:
      server-addr: 192.168.74.101:8848 #nacos地址 为了服务拉取
    gateway:
      routes: #路由配置
        - id: item-service #建议和微服务的名字保持一致
          uri: lb://item-service #lb://前缀表示负载均衡，后面跟微服务的名字
          predicates: #路由的断言 name args path路径做匹配 controller路径是什么
            - Path=/items/**,/search/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: trade
          uri: lb://trade-service
          predicates:
              - Path=/orders/**
      default-filters:
        - AddRequestHeader=truth,anyone long-press like button will be rich #默认的过滤器 对所有的路由都生效
        - PrintAny=1,2,3
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123 # 解析文件的密码
    tokenTTL: 30m
  auth:
    excludePaths: # 不需要认证的接口 通过authproperites 读取
      - /search/**
      - /users/login
      - /items/**
      - /hi
